In [4]:
# importing Numpy package
import numpy as np
  
# creating a 4X4 Numpy matrix
n_array = np.array([[5, 2, 1, 4],
                    [9, 4, 2, 5],
                    [11, 5, 7, 3],
                    [5, 6, 6, 7]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 4X4 square matrix:")
print(int(det))

Numpy Matrix is:
[[ 5  2  1  4]
 [ 9  4  2  5]
 [11  5  7  3]
 [ 5  6  6  7]]

Determinant of given 4X4 square matrix:
239
